// Source: google/gemma-4-26B-A4B-it (https://huggingface.co/google/gemma-4-26B-A4B-it)
// License: apache-2.0
// Generated: 2026-07-19T10:27:40+0000
// Auto-generated by script/build-bridge.py — do not edit manually

export declare const BRIDGE_OFFSETS: number[];
export declare const BRIDGE_PAIRS: number[];
