// Auto-generated by scripts/prepare-vocab.ts — do not edit manually
// Vocab: 262144 tokens, Merges: 514906
export declare const GEMMA_UNK_ID: number
export declare const GEMMA_VOCAB: Record<string, number>
export declare const GEMMA_MERGES: [string, string][]
