// Source: google/gemma-4-26B-A4B-it (https://huggingface.co/google/gemma-4-26B-A4B-it)
// License: apache-2.0
// Generated: 2026-07-18T10:41:04+0000
// Auto-generated by script/generate_vocab.py — do not edit manually

export declare const UNK_ID: number;
export declare const VOCAB: Record<string, number>;
export declare const MERGES: [string, string][];
